version: "3.8"

services:
  app:
    build: .
    command: python ht-tracker.py
    ports:
      - 192.168.1.103:8002:12346
    volumes:
      - type: bind
        source: ./data
        target: /data